version: 2
updates:
  - package-ecosystem: cargo
    directories: ["/programs/conversations-blogpost", "/programs/count_movies", "/programs/preprocess_latex", "/programs/web_sound"]
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/ts"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
